- name: Configuring the repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Installing Filebeat
  ansible.builtin.dnf:
    name: filebeat
    state: installed

- name: Configuring filebeat 
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Starting ELK Services
  ansible.builtin.systemd_service:
    name: filebeat
    state: restarted
    enabled: true