- name: Demo on using shell module 
  hosts: all 
  gather_facts: false                # By default, this value is true
  tasks:
    - name: Pritning a fact  
      ansible.builtin.shell: uptime 
      register: OUTPUT

    - name: Pritning output
      ansible.builtin.debug:
        msg: "{{OUTPUT.stdout}}"