- name: Configuring hostname 
  ansible.builtin.shell: set-hostname "{{COMPONENT}}"

- name: Disabling Nodejs                                    # For disabling and enabling nodejs, we didn't find the relevant ansible module
  ansible.builtin.shell: dnf module disable nodejs -y 

- name: Enabling Nodejs                                    # For disabling and enabling nodejs, we didn't find the relevant ansible module
  ansible.builtin.shell: dnf module enable nodejs:20 -y 

- name: Installing nodejs 
  ansible.builtin.dnf:
    name: nodejs 
    state: present 

- name: Adding app user expense 
  ansible.builtin.user:
    name: expense
    comment: Application User 

- name: Cleanup Of Old App Directory
  ansible.builtin.file:
    path: "{{APP_PATH}}"
    state: absent

- name: Creating App Directory
  ansible.builtin.file:
    path: "{{APP_PATH}}"
    state: directory

- name: Download & Extracting {{COMPONENT}}
  ansible.builtin.unarchive:
    src: https://expense-web-app.s3.amazonaws.com/{{COMPONENT}}.zip
    dest: "{{APP_PATH}}"
    remote_src: yes    

- name: Generating node_modules
  community.general.npm:
    path: "{{APP_PATH}}"

- name: Install MySQL Client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Install Prereq packages for mysql_db
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography                     
    executable: pip3.11

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: root
    login_password: "{{PWD}}"
    login_host: mysql.expense.internal

- name: Copying Systemd file 
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Restarting {{COMPONENT}}
  ansible.builtin.systemd_service:
    name: "{{COMPONENT}}" 
    state: restarted
    enabled: true
    daemon_reload: true