- name: Configuring hostname 
  ansible.builtin.shell: set-hostname "{{COMPONENT}}-{{ENV}}"

- name: Configuring Node Exporter
  ansible.builtin.include_role:     
    name: prometheus                 
    tasks_from: node-exporter